"""
Surface file reader (migrated from Script01_lectura_caras_vertices.py)
Reads MSMS vertex and face files generated by MSMS software
"""
import re
from typing import Tuple, List
from app.core.logging import get_logger

logger = get_logger(__name__)


def read_surface_files(vertices_file: str, faces_file: str) -> Tuple[List[List[str]], List[List[str]]]:
    """
    Read MSMS vertex and face files

    MSMS (Michel Sanner's Molecular Surface) generates:
    - .vert files: vertices with coordinates, normals, areas, and face types
    - .face files: triangular faces connecting vertices

    Args:
        vertices_file: Path to .vert file
        faces_file: Path to .face file

    Returns:
        Tuple of (vertices_array, faces_array)
        - vertices_array: List of lists with 11 columns per vertex
        - faces_array: List of lists with 6 columns per face

    File Format:
        .vert: First 3 lines are headers (skipped)
               Format: x y z nx ny nz area unused face_type ...
        .face: First 3 lines are headers (skipped)
               Format: v1 v2 v3 face_type unused ...

    Note: This preserves ALL data from the original files, not just coordinates
    """
    logger.info(f"Reading MSMS surface files")
    logger.info(f"  Vertices file: {vertices_file}")
    logger.info(f"  Faces file: {faces_file}")

    # Read vertices file
    try:
        with open(vertices_file, 'r') as f:
            f_vert = f.readlines()
    except FileNotFoundError:
        logger.error(f"Vertices file not found: {vertices_file}")
        raise
    except Exception as e:
        logger.error(f"Error reading vertices file: {str(e)}")
        raise

    # Parse vertices (skip first 3 header lines)
    rows_vert = len(f_vert) - 3
    cols_vert = 11
    arr_vert = []

    count_vert = 0
    for line in f_vert:
        if count_vert > 2:  # Skip header lines
            # Split by one or more spaces
            split_line = re.split(r' +', line.strip())
            if len(split_line) >= cols_vert:
                arr_vert.append(split_line[:cols_vert])
            else:
                # Pad with empty strings if needed
                split_line.extend([''] * (cols_vert - len(split_line)))
                arr_vert.append(split_line)
        count_vert += 1

    # Read faces file
    try:
        with open(faces_file, 'r') as f:
            f_face = f.readlines()
    except FileNotFoundError:
        logger.error(f"Faces file not found: {faces_file}")
        raise
    except Exception as e:
        logger.error(f"Error reading faces file: {str(e)}")
        raise

    # Parse faces (skip first 3 header lines)
    rows_face = len(f_face) - 3
    cols_face = 6
    arr_face = []

    count_face = 0
    for line in f_face:
        if count_face > 2:  # Skip header lines
            split_line = re.split(r' +', line.strip())
            if len(split_line) >= cols_face:
                arr_face.append(split_line[:cols_face])
            else:
                # Pad with empty strings if needed
                split_line.extend([''] * (cols_face - len(split_line)))
                arr_face.append(split_line)
        count_face += 1

    logger.info(f"Successfully loaded {len(arr_vert)} vertices and {len(arr_face)} faces")
    logger.info("MSMS surface files read complete")

    return arr_vert, arr_face
