"""Initial database schema

Revision ID: 001
Revises:
Create Date: 2025-11-14

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###

    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('jobs_count', sa.Integer(), nullable=True),
    sa.Column('last_job_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create proteins table
    op.create_table('proteins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stl_file', sa.String(), nullable=True),
    sa.Column('vertices_file', sa.String(), nullable=True),
    sa.Column('faces_file', sa.String(), nullable=True),
    sa.Column('cr_totals_file', sa.String(), nullable=True),
    sa.Column('context_rays_file', sa.String(), nullable=True),
    sa.Column('centroid_count', sa.Integer(), nullable=True),
    sa.Column('layer_files', sa.JSON(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proteins_id'), 'proteins', ['id'], unique=False)
    op.create_index(op.f('ix_proteins_name'), 'proteins', ['name'], unique=False)
    op.create_index(op.f('ix_proteins_user_id'), 'proteins', ['user_id'], unique=False)
    op.create_index('idx_proteins_user_created', 'proteins', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_proteins_user_name', 'proteins', ['user_id', 'name'], unique=False)

    # Create jobs table
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.Enum('PART_ONE', 'PART_TWO', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('input_files', sa.JSON(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_params', sa.JSON(), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_protein_id'), 'jobs', ['protein_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index('idx_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_jobs_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_jobs_user_status', 'jobs', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index('idx_jobs_user_status', table_name='jobs')
    op.drop_index('idx_jobs_user_created', table_name='jobs')
    op.drop_index('idx_jobs_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_protein_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')

    op.drop_index('idx_proteins_user_name', table_name='proteins')
    op.drop_index('idx_proteins_user_created', table_name='proteins')
    op.drop_index(op.f('ix_proteins_user_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_name'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_id'), table_name='proteins')
    op.drop_table('proteins')

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
